import Head from 'next/head'
import '../styles/globals.css'

export const metadata = {
  title: 'Manga',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon.png',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  )
}
